nohup python trainer.py \
--max_seq_len 512 \
--num_train_epochs 5 \
--lr_scheduler_type cosine \
--learning_rate 0.0003 \
--warmup_ratio 0.25 \
--weight_decay 0.35 \
--per_device_train_batch_size 16 \
--per_device_eval_batch_size 16 \
--save_total_limit 1 \
--model_base  t5-base \
--run_id t5_base_model_3 \
--output_dir trained_models_mtl/  >> training_logs_t7.out &